### PR TITLE
feat: fixed base fee

### PR DESCRIPTION
**Pull request by clostao**
## Description

Fixed base fee using pallet_base_fee support to ease upcoming upgrades. 

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by GabrielMartinezRodriguez — APPROVED** [review]
LGTM

**Review by deblanco — DISMISSED** [review]
another one!

**Review by deblanco — APPROVED** [review]
awesome

**Review by GabrielMartinezRodriguez — APPROVED** [review]
LGTM

**Pull request merged**
